version: "3.7"
 
services:
  db:
    container_name: parser_db
    image: postgres:14.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.db.env
    ports:
      - "5432:5432"

  web:
    container_name: parser_app
    image: web-parser
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 200
    volumes:
      - .:/web-parser
      - static:/parser/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.dev.env
    depends_on:
      - db

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l INFO
    entrypoint: [ "/parser/entrypoint.sh" ]
    env_file:
      - ./.dev.env
      - ./.db.env
    depends_on:
      - redis

  nginx:
    container_name: parser_web
    build: ./nginx
    volumes:
      - static:/staticfiles/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres:
  static: